### ISSUE TITLE
Feedback from @spectator

### ISSUE THREAD

**Issue by dangershony** [stratisproject/Breeze#137]
1) Make buttons and font bigger.
2) Make each row clickable for latest transactions so we dont have to aim the "details" link to see details.
3) When you have 0 tbtc, and you try to send there should be a popup that prevents them from sending. At the moment, no error msg.
4) close button should send wallet to system tray rather than closing the wallet.
5) confirmations for transactions 9/52 confirmation thing that shows us progress. Maybe for aesthetics you can add a progress bar.
6) when we receive tokens, a popup by system tray should notify us like the stratis qt wallet.
7) Use max button for sending
8) it showed 1.3 tbtc in my active balance, i sent .12 tbtc to someone and my active balance shos 0.3 tbtc and it moved the rest to unconfirmed balance. Then a few seconds later it moved back to active balance.

**Comment by dev0tion** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] Check payment amount](https://trello.com/c/oVBlpLQs/86-wallet-gui-check-payment-amount)

**Comment by dev0tion** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] Show confirmations](https://trello.com/c/S7enWTyG/87-wallet-gui-show-confirmations)

**Comment by dev0tion** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] Add native notifications](https://trello.com/c/Bt4u4OcC/88-wallet-gui-add-native-notifications)

**Comment by dev0tion** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet] Add "max" function to API](https://trello.com/c/VxsOrqcX/89-wallet-add-max-function-to-api)

**Comment by dev0tion** [comment]
1) Design on buttons and font are found OK by us
2) We have considered this, but it will be popping up a modal every time a user accidentally clicks a transaction. To be continued.
3) Fixed in #155 
4) Closing will behave like a native app will behave. In Windows/Linux the app will shut down. In OS X the app will minimize.
5) This will be added in the current sprint
6) Native notifications are planned for another sprint
7) Max button is already there, just commented out. We need to add an API method for this. It will happen in another sprint.
8) This is how it actually works with all wallets, but we are working on displaying it differently so users don't know about it.
