### ISSUE TITLE
[Priority: High] Wallet Recovery Bug

### ISSUE THREAD

**Issue by nopara73** [stratisproject/Breeze#210]
If one recovers the same wallet it already has in `StratisNode\bitcoin\TestNet` folder, the recovery will fail with an error, but the recovered wallet is in the folder.  
However it will prevent running the software again. Manually deleting the recovered wallet will fix the issue.  

![](http://i.imgur.com/Fll5d5u.png)  
  
## Expected behaviour  
Let the user recover the already existing wallet, because it might want to recover with a different syncing start.

**Comment by bokobza** [comment]
ah brilliant, we had this before but I couldn't reproduce it.
Thanks for stumbling upon it!

**Comment by bokobza** [comment]
https://trello.com/c/fm6TtRz8/191-wallet-recover-existing-wallet-throws-exception

**Comment by bokobza** [comment]
So instead of allowing the user to create another wallet in parallel, we advise the user to delete the file if he's keen to restore the wallet anyway.
The problem with having the same wallet twice is that it's wasteful when looking for transactions on the network, and it might get confusing if the two wallets have different balances or are generally out of sync.

**Comment by bokobza** [comment]
closed with https://github.com/stratisproject/StratisBitcoinFullNode/pull/435
