### ISSUE TITLE
Clicking the 'send' button multiple times

### ISSUE THREAD

**Issue by matje123** [stratisproject/Breeze#229]
It is possible to click the send button multiple times after each other while the transaction is processing.
Only 1x btc is sent out, but it shows up multiple times in my receiving wallet (they do not get confirmed).

I would suggest making something that after the first click on the send button a message shows up when you click another time before the transaction is finished ('please wait while your transaction is beeing processed') or something like that.

**Comment by nopara73** [comment]
Hi @matje123.  
I am not sure how the wallet would currently work at sending, but even if it was working improperly before it won't in the future, because I just implemented sending properly yesterday: https://github.com/stratisproject/StratisBitcoinFullNode/pull/486  

> I would suggest making something that after the first click on the send button a message shows up when you click another time before the transaction is finished ('please wait while your transaction is beeing processed') or something like that.  

My implementation only touches the API, but as you suggest it also must be fixed in the UI. We have an issue for that already: https://github.com/stratisproject/Breeze/issues/207

**Comment by dev0tion** [comment]
I've disabled some buttons on API calls.
I will talk to @bep42 how we will show it properly to the users that something is currently ongoing in the background.

Issue on OP is fixed, will continue in #207.
