### ISSUE TITLE
Cant send TSTRAT

### ISSUE THREAD

**Issue by mtaipe** [stratisproject/Breeze#274]
Have funds and entered the correct password.

After click send, it change to grey, after few seconds the fee shows and the button keeps grey for few seconds and then becomes available, the form doesnt closes. No records in the history and no message confirming the TX. The Balance remains as initial state.

**Comment by nopara73** [comment]
This has been fixed yesterday, the problem was the Stratis test network refused the propagation, due to too low fee: https://github.com/stratisproject/StratisBitcoinFullNode/pull/543  
Why this happens to you is because the StratisBitcoinFullNode submodule had not been updated in the Breeze repository.

**Comment by dev0tion** [comment]
I can reproduce this on Ubuntu. Not in Windows and OS X.
Investigating.

**Comment by nopara73** [comment]
Sending transactions works on Ubuntu.  
What is the problem? Light wallet does not have mempool, therefore it cannot make sure the transaction is valid. So what is the solution? Broadcast to half of the peers and wait for the other half of the peers to broadcast the transaction back to us.  

The problem is, there's just very few Stratis testnet nodes, in fact I have 2 on Windows, and for some reason it only connects to one on Ubuntu.  
What happens is: it broadcasts to the one node it connects to, then it has no idea if the broadcast was successful or not, until the node sends us a block.  
This is fine behavior and it does not happen on stratis and bitcoin mainnet and on bitcoin testnet, because there are more nodes.  

In the end the wallet will know about the transaction when it confirms.  

@dev0tion You might want to add a warning about this when there is only one connected node, or leave it like this.
