### ISSUE TITLE
Make text clearer in wallet recovery modal

### ISSUE THREAD

**Issue by bokobza** [stratisproject/Breeze#295]
When creating a wallet, the modal shown says that in order to recover the wallet, the users needs to save their mnemonic, their password and the wallet creation time.
However, wallet creation time is not compulsory to recover the wallet.
Something that says:

> In addition, knowing the approximate date at which you created your wallet will speed up recovery.

would be clearer.

**Comment by mikeolteanu** [comment]
Important because it seems to imply that you might not be able to recover your wallet if you don't have the wallet creation time - Which implies risk to funds, if you don't have the correct wallet creation time - down to the second? with the timezone? It is ambiguous in a way that is disconcerting as a threat to funds

**Comment by dev0tion** [comment]
Done in #327
